name: CD Pipeline
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 400 private_key.pem  # Using chmod 400

      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e  # Stop execution if any command fails

            echo "Switching to project directory..."
            cd /home/ubuntu/fastapi-book-project || exit 1

            echo "Pulling latest code..."
            git fetch --all
            git reset --hard origin/main
            git pull origin main

            echo "Stopping existing containers..."
            docker-compose down

            echo "Rebuilding and starting Docker containers..."
            docker-compose up -d --build

            echo "Deployment successful!"
