name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "✅ SSH connection successful!"
            
            # Navigate to project folder
            cd /home/ubuntu/fastapi-book-project

            # Pull latest changes
            git fetch --all
            git reset --hard origin/main
            git pull origin main

            # Restart Docker containers
            docker-compose down
            docker-compose up -d --build
