name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Decode and Set Up SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY_B64 }}" | base64 --decode > fastapi.pem
          chmod 400 fastapi.pem
          cat fastapi.pem # Debugging step to confirm key exists

      - name: SSH into EC2 and Deploy
        env:
          SSH_USER: "ubuntu"
          SSH_HOST: "54.172.128.146"  # Replace with your EC2 Public IP
        run: |
          ssh -o StrictHostKeyChecking=no -i fastapi.pem $SSH_USER@$SSH_HOST << 'EOF'
            cd /home/ubuntu/app
            git pull origin main
            docker compose down
            docker compose up -d --build
          EOF

      - name: Cleanup SSH Key
        run: rm -f fastapi.pem
