name: CD Pipeline
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode and Save SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > private_key.pem
          chmod 600 private_key.pem  # Secure key file

      - name: Add EC2 Instance to Known Hosts
        run: |
          mkdir -p ~/.ssh  # Ensure the .ssh directory exists
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts  # Debug: Check the file

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e  # Stop execution on error

            echo "Switching to project directory..."
            cd /home/ubuntu/fastapi-book-project || exit 1

            echo "Pulling latest code..."
            git fetch --all
            git reset --hard origin/main
            git pull origin main

            echo "Stopping existing containers..."
            docker-compose down

            echo "Rebuilding and starting Docker containers..."
            docker-compose up -d --build

            echo "Deployment successful!"
