name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the app directory
            cd /home/ubuntu/fastapi-app || git clone https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME.git fastapi-app
            cd /home/ubuntu/fastapi-app

            # Pull latest changes
            git checkout main
            git pull origin main

            # Build and run the Docker container
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker build -t fastapi-app .
            docker run -d --name fastapi-app -p 8000:8000 fastapi-app

            # Restart Nginx
            sudo systemctl restart nginx
